Repository RustPython/RustPython, pull requests merged in 2023-04, with the labels that each got.

#4790 Modify unary & ternary function fields in number protocol
  Lib/test/test_descr.py
  vm/src/builtins/complex.rs
  vm/src/builtins/float.rs
  vm/src/builtins/int.rs
  vm/src/frame.rs
  vm/src/protocol/mod.rs
  vm/src/protocol/number.rs
  vm/src/stdlib/builtins.rs
  vm/src/stdlib/operator.rs
  vm/src/types/slot.rs
  vm/src/vm/vm_ops.rs
Labels: C-compat, A-design, A-vm

#4764 test_os windows failed test handling
  .github/workflows/ci.yaml
  Lib/test/test_os.py
Labels: E-help-wanted, A-stdlib, O-windows

#4896 RUST_BACKTRACE=1 for debugger
  .vscode/launch.json
Labels: skip:ci

#4897 Reduce runtime of stdlib_collections_deque
  extra_tests/snippets/stdlib_collections_deque.py
Labels: skip:ci

#4916 run choco with --no-progress
  .github/workflows/ci.yaml
Labels: skip:ci
