Repository RustPython/RustPython, pull requests merged in 2023-02, with the labels that each got.

#4526 Update hmac.py to CPython 3.11 and integrate test_hmac.py tests
  Cargo.lock
  Lib/hmac.py
  Lib/test/test_hashlib.py
  Lib/test/test_hmac.py
  stdlib/Cargo.toml
  stdlib/src/hashlib.rs
Labels: zls-2023

#4534 Copy graphlib module from cpython
  Lib/graphlib.py
  Lib/test/test_graphlib.py
Labels: zls-2023

#4533 Implemented the block_size attribute for PyHasher
  Lib/test/test_hmac.py
  stdlib/src/hashlib.rs
Labels: zls-2023

#4549 Mark RustPython as Python 3.11
  vm/src/version.rs
Labels: A-packaging

#4548 Prepare to implement hash for tuple
  vm/src/builtins/range.rs
  vm/src/builtins/tuple.rs
Labels: C-enhancement, A-stdlib

#4543 Flatten parser interface
  benches/execution.rs
  compiler/ast/src/constant.rs
  compiler/codegen/src/compile.rs
  compiler/core/src/location.rs
  compiler/core/src/mode.rs
  compiler/parser/python.lalrpop
  compiler/parser/src/error.rs
  compiler/parser/src/function.rs
  compiler/parser/src/lexer.rs
  compiler/parser/src/lib.rs
  compiler/parser/src/mode.rs
  compiler/parser/src/parser.rs
  compiler/parser/src/soft_keywords.rs
  compiler/parser/src/string.rs
  compiler/src/lib.rs
  examples/parse_folder.rs
  src/shell.rs
  vm/src/dictdatatype.rs
  vm/src/object/core.rs
  vm/src/stdlib/ast.rs
  vm/src/stdlib/builtins.rs
  wasm/lib/src/convert.rs
Labels: A-compiler

#4165 Fix `property.__set_name__` error message when arguments are invalid
  Lib/test/test_property.py
  vm/src/builtins/property.rs
Labels: z-ca-2022

#4560 Update unittest from CPython 3.11
  Lib/unittest/__init__.py
  Lib/unittest/async_case.py
  Lib/unittest/case.py
  Lib/unittest/loader.py
  Lib/unittest/main.py
  Lib/unittest/mock.py
  Lib/unittest/result.py
  Lib/unittest/runner.py
  Lib/unittest/test/__init__.py
  Lib/unittest/test/test_async_case.py
  Lib/unittest/test/test_break.py
  Lib/unittest/test/test_case.py
  Lib/unittest/test/test_discovery.py
  Lib/unittest/test/test_functiontestcase.py
  Lib/unittest/test/test_loader.py
  Lib/unittest/test/test_program.py
  Lib/unittest/test/test_result.py
  Lib/unittest/test/test_runner.py
  Lib/unittest/test/test_skipping.py
  Lib/unittest/test/test_suite.py
  Lib/unittest/test/testmock/testasync.py
  Lib/unittest/test/testmock/testmock.py
  Lib/unittest/test/testmock/testwith.py
Labels: A-stdlib

#4559 Add (fake) frozenmodule __origname__ and _imp.find_frozen
  .cspell.json
  vm/build.rs
  vm/src/import.rs
  vm/src/stdlib/imp.rs
Labels: A-stdlib

#4578 attach links to images
  README.md
Labels: skip:ci

#4587 Fix CR/LF of python libraries
  Lib/test/test_bigmem.py
  Lib/test/test_buffer.py
  Lib/test/test_cgitb.py
  Lib/test/test_cmd_line.py
  Lib/test/test_cmd_line_script.py
  Lib/test/test_code_module.py
  Lib/test/test_contextlib.py
  Lib/test/test_dummy_thread.py
  Lib/test/test_dummy_threading.py
  Lib/test/tracedmodules/__init__.py
  Lib/test/tracedmodules/testmod.py
Labels: A-stdlib

#4586 Update trace from CPython 3.11.2
  Lib/test/test_trace.py
  Lib/trace.py
Labels: A-stdlib

#4558 Add localeconv function to locale module
  Lib/test/test_locale.py
  Lib/test/test_types.py
  stdlib/src/lib.rs
  stdlib/src/locale.rs
Labels: z-ls-2023
