Repository RustPython/RustPython, pull requests merged in 2023-06, with the labels that each got.

#5003 Remove deprecated modules binhex and formatter.
  Lib/binhex.py
  Lib/formatter.py
Labels: A-stdlib, C-cleanup

#5006 Set correct output file
  .github/workflows/cron-ci.yaml
Labels: skip:ci

#4773 Fix test_path_like_objects
  Lib/test/test_compile.py
  Lib/test/test_runpy.py
  vm/src/stdlib/builtins.rs
  vm/src/stdlib/os.rs
Labels: A-stdlib, z-ca-2023
