Repository RustPython/RustPython, pull requests merged in 2023-03, with the labels that each got.

#4524 Custom marshal enc/decoding impl
  Cargo.lock
  compiler/Cargo.toml
  compiler/codegen/Cargo.toml
  compiler/codegen/src/compile.rs
  compiler/codegen/src/error.rs
  compiler/codegen/src/ir.rs
  compiler/core/Cargo.toml
  compiler/core/src/bytecode.rs
  compiler/core/src/error.rs
  compiler/core/src/lib.rs
  compiler/core/src/location.rs
  compiler/core/src/marshal.rs
  compiler/parser/Cargo.toml
  compiler/parser/src/parser.rs
  compiler/src/lib.rs
  vm/Cargo.toml
  vm/src/builtins/code.rs
  vm/src/builtins/complex.rs
  vm/src/builtins/dict.rs
  vm/src/builtins/float.rs
  vm/src/builtins/function.rs
  vm/src/builtins/function/jitfunc.rs
  vm/src/builtins/traceback.rs
  vm/src/exceptions.rs
  vm/src/frame.rs
  vm/src/lib.rs
  vm/src/macros.rs
  vm/src/stdlib/marshal.rs
  wasm/lib/Cargo.toml
Labels: C-enhancement, A-compiler, A-stdlib

#4603 Add strxfrm and strcoll to locale mod
  Lib/test/test_locale.py
  stdlib/src/locale.rs
Labels: z-ls-2023

#4610 Implementing shake_128 and shake_256 in the hashlib module
  Lib/test/test_hashlib.py
  stdlib/src/hashlib.rs
Labels: z-ls-2023

#4651 Add ArgIndex according to #4629
  vm/src/function/number.rs
Labels: z-ls-2023

#4640 Update to pass test for unhashable collections
  Lib/test/test_collections.py
  Lib/test/test_typing.py
  derive-impl/src/pyclass.rs
  derive-impl/src/util.rs
  vm/src/builtins/bytearray.rs
  vm/src/builtins/dict.rs
  vm/src/builtins/list.rs
  vm/src/builtins/set.rs
  vm/src/builtins/slice.rs
  vm/src/builtins/type.rs
  vm/src/class.rs
  vm/src/stdlib/collections.rs
  vm/src/types/slot.rs
Labels: z-ls-2023

#4671 Fix typo in number.rs
  vm/src/function/number.rs
Labels: skip:ci

#4615 Improve: binary ops with Number Protocol
  Lib/test/test_collections.py
  Lib/test/test_enum.py
  Lib/test/test_xml_dom_minicompat.py
  common/src/str.rs
  derive-impl/src/pyclass.rs
  rust-toolchain
  rust-toolchain.toml
  stdlib/src/array.rs
  vm/src/builtins/bool.rs
  vm/src/builtins/bytearray.rs
  vm/src/builtins/bytes.rs
  vm/src/builtins/complex.rs
  vm/src/builtins/dict.rs
  vm/src/builtins/float.rs
  vm/src/builtins/int.rs
  vm/src/builtins/mappingproxy.rs
  vm/src/builtins/set.rs
  vm/src/builtins/singletons.rs
  vm/src/builtins/str.rs
  vm/src/builtins/type.rs
  vm/src/builtins/union.rs
  vm/src/protocol/mod.rs
  vm/src/protocol/number.rs
  vm/src/protocol/sequence.rs
  vm/src/stdlib/builtins.rs
  vm/src/stdlib/io.rs
  vm/src/types/slot.rs
  vm/src/vm/context.rs
  vm/src/vm/vm_ops.rs
Labels: C-enhancement, C-compat, A-design, z-ls-2023, A-vm

#4652 Add locale implementation for windows
  Lib/test/test_locale.py
  stdlib/Cargo.toml
  stdlib/src/lib.rs
  stdlib/src/locale.rs
Labels: A-stdlib, z-ls-2023, O-windows

#4747 update test from test_pwd cpython 3.11.2
  Lib/test/test_pwd.py
Labels: A-stdlib

#4744 Update glob.py and test/test_glob.py from CPython v3.11.2
  Lib/glob.py
  Lib/test/test_glob.py
Labels: A-stdlib

#4746 Update test_bytes.py from CPython v3.11.2
  Lib/test/test_bytes.py
Labels: A-stdlib

#4748 Fix int.from_bytes and Update random.py and test/test_random.py from CPython v3.11.2
  Lib/random.py
  Lib/test/test_random.py
  vm/src/builtins/int.rs
Labels: C-bug, A-stdlib, z-ca-2023

#4756 resolve unittest error in test_sort.py
  Lib/test/test_sort.py
  vm/src/iter.rs
Labels: C-bug, A-stdlib, z-ca-2023

#4767 Add Hash and Iter of WeakProxy.rs for test\testWeakref.py
  Lib/test/test_weakref.py
  vm/src/builtins/weakproxy.rs
Labels: A-stdlib, z-ca-2023

#4766 Allow try_update_quantity_from_tuple to set left alignment when needed
  Lib/test/test_bytes.py
  vm/src/cformat.rs
Labels: A-stdlib, z-ca-2023

#4776 changed builtins.rs to resolve test case error in test_builtin.py
  Lib/test/test_builtin.py
  vm/src/stdlib/builtins.rs
Labels: A-stdlib, z-ca-2023

#4772 update string_tests and solve failing test
  Lib/test/string_tests.py
  vm/src/builtins/str.rs
  vm/src/bytesinner.rs
Labels: A-stdlib, z-ca-2023

#4782 relocate FsPath from stdlib::os and rename PyPathLike to OsPath
  common/src/os.rs
  stdlib/src/posixsubprocess.rs
  stdlib/src/socket.rs
  stdlib/src/sqlite.rs
  stdlib/src/ssl.rs
  vm/src/function/fspath.rs
  vm/src/function/mod.rs
  vm/src/stdlib/io.rs
  vm/src/stdlib/nt.rs
  vm/src/stdlib/os.rs
  vm/src/stdlib/posix.rs
  vm/src/stdlib/posix_compat.rs
Labels: C-bug, A-design, C-cleanup

#4794 Add --features ssl to README
  README.md
Labels: skip:ci
