Repository RustPython/RustPython, pull requests merged in 2025-04, with the labels that each got.

#5680 Remove packaging from release
  .github/workflows/release.yml
Labels: skip:ci

#5724 Update webbrowser and test_webbrowser to 3.13.3
  Lib/test/test_webbrowser.py
  Lib/webbrowser.py
Labels: A-stdlib

#5747 Collect whats_left data for website with sqlite feature
  .github/workflows/cron-ci.yaml
Labels: skip:ci

#5590 typing upgrade to 3.13.2
  Lib/_py_abc.py
  Lib/test/support/testcase.py
  Lib/test/test_dataclasses.py
  Lib/test/test_exception_group.py
  Lib/test/test_future_stmt/test_future.py
  Lib/test/test_genericalias.py
  Lib/test/test_types.py
  Lib/test/test_typing.py
  Lib/test/typinganndata/_typed_dict_helper.py
  Lib/test/typinganndata/ann_module695.py
  Lib/test/typinganndata/mod_generics_cache.py
  Lib/typing.py
  vm/src/stdlib/typing.rs
Labels: A-stdlib, cpython

#5719 copilot-instructions
  .github/copilot-instructions.md
Labels: skip:ci

#5743 Support multiline function/class definitions in REPL and InteractiveConsole
  Lib/codeop.py
  src/shell.rs
Labels: C-enhancement

#5761 Fix Cargo.lock
  Cargo.lock
Labels: skip:ci

#5716 Cleaner panic output for codegen errors
  compiler/codegen/src/compile.rs
  compiler/codegen/src/error.rs
  compiler/codegen/src/ir.rs
  compiler/codegen/src/lib.rs
Labels: A-compiler, C-cleanup
